name: land_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - rasterio
  - shapely
  - unidecode
  - pyyaml
  - pandas
  - matplotlib
  - numpy
  - pygadm
  - shapely
  - jupyter
  - ipython
  - ipykernel